server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#server:
#  port: 8082
#spring:
#    application:
#      name: service-hi

# druid datasource setting
#spring.datasource.name=a520
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/a520?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=xue881120
##spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.filters=stat
#spring.datasource.maxActive=20
#spring.datasource.initialSize=1
#spring.datasource.maxWait=60000
#spring.datasource.minIdle=1
#spring.datasource.timeBetweenEvictionRunsMillis=60000
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=select 'x'
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxOpenPreparedStatements=20
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database=MYSQL
#spring.jpa.show-sql=true